### ISSUE TITLE
Lambda Function: Fetch and return resume data based on an id.

### ISSUE THREAD

**Issue by KerrilOte** [KerrilOte/Cloud-Resume-API#2]
### TASKS

- [ ] Define a lambda function
- [ ] Write lambda function to fetch data from DynamoDB
- [ ] Create a function URL
