### ISSUE TITLE
Create AWS architectural diagram  and Readme file

### ISSUE THREAD

**Issue by KerrilOte** [KerrilOte/Cloud-Resume-API#5]
### TASKS
- [ ] Create architectural diagram 
- [ ] write Readme file

**Comment by KerrilOte** [comment]
- [ ]  write the readme.md file detailing the theoretical step by step guide
- [ ] Attach Lucid chart or Draw.io file of the  architectural diagram 
- [ ] update the readme file at every step
